//
// Created by windperson on 10/7/2016.
//

#ifndef ANDROIDSTUDIIOCOMBINENDKDEMO_NATIVE_LOGIC_H
#define ANDROIDSTUDIIOCOMBINENDKDEMO_NATIVE_LOGIC_H


class native_logic {

};


#endif //ANDROIDSTUDIIOCOMBINENDKDEMO_NATIVE_LOGIC_H
